apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: another-inner-loop-java
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: another-inner-loop
spec:
  source:
    git:
      url: https://github.com/x95castle1/jeremy-java-web-app
      ref:
        branch: main
