apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: another-inner-loop
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: another-inner-loop
    apps.tanzu.vmware.com/has-tests: true
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/x95castle1/jeremy-java-web-app
      ref:
        branch: main
